language: ruby

before_install: 
  - "cd vendor/oclc-auth-ruby"
  - "gem build oclc-auth.gemspec"
  - "gem install oclc-auth"
  - "cd ../worldcat-discovery-ruby"
  - "gem build worldcat-discovery.gemspec"
  - "gem install worldcat-discovery"
  - "cd ../cedilla_service_commons"
  - "gem build cedilla.gemspec"
  - "gem install cedilla"

rvm:
  - "2.1.2"
  - "2.0.0"
