language: ruby

before_install: "git submodule init && git submodule update && sudo gem update --system && cd /vendor/oclc-auth-ruby && sudo gem build oclc-auth.gemspec && sudo gem install oclc-auth && cd ../worldcat-discovery-ruby && sudo gem build worldcat-discovery.gemspec && sudo gem install worldcat-discovery && cd ../cedilla_service_commons && sudo gem build cedilla.gemspec && sudo gem install cedilla && cd ../.. && sudo gem install bundler && bundle install"

rvm:
  - "2.1.2"
  - "2.0.0"
